In [1]:
''' LIBRARIES '''
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import re
import time
from IPython.display import clear_output

from fuzzywuzzy import process, fuzz
from sympy import symbols, Eq, solve
import pandas as pd
import numpy as np

c:\Users\KNL\AppData\Local\Programs\Python\Python39\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

# PINNACLE
## Prematch

In [2]:
'''                               PREMATCH pinnacle NAVIGATOR''' 


url_pin_prematch = 'https://www.pinnacle.com/en/soccer/matchups/highlights'
#changing chromedriver default options
options = Options()
options.add_argument('window-size=1920x1080') #Headless = True
options.headless = True #for not opening the navigator
#Headless = True

pin_prematch = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
pin_prematch.get(url_pin_prematch)

C:\Users\KNL\AppData\Local\Temp\ipykernel_2136\1708381777.py:11: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  pin_prematch = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [3]:
''' FUNCTION pinnacle_prematch ''' 
def pinnacle_prematch():
    i=2
    df_pre_pinnacle=pd.DataFrame(columns=['teams', '1_pin','X_pin','2_pin', 'goals',  'over','under'])
    while i<30:
        i+=1
        try:
            #home_team = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[0]
            #away_team = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[1]
            teams = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[0]+' '+pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[1]
            h_wins = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[3]
            X      = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[4]
            a_wins = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[5]
            
            goals = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[10]
            over  = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[11]
            under = pin_prematch.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(i)).text.split('\n')[12]
            
            df_pre_pinnacle.loc[len(df_pre_pinnacle.index)] = [teams,  h_wins, X, a_wins, goals,  over, under]

            
        except:
            pass

    return df_pre_pinnacle

# Live PINNACLE

In [3]:
'''                                  PINNCALE NAVIGATOR TO THE BACKGROUND'''


url_pin = 'https://www.pinnacle.com/en/soccer/matchups/live'

#changing chromedriver default options
options = Options()
options.headless = True #for not opening the navigator
options.add_argument('window-size=1920x1080') #Headless = True
pin = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
pin.get(url_pin)

C:\Users\KNL\AppData\Local\Temp\ipykernel_25640\3605115053.py:10: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  pin = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [45]:
'''           function LIVE PINNACLE'''


def pinnacle():
    #pin = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
    #pin.get(url_pin)
    j = 1 # ITS 2(AND IN THE BEGGINING OF THE LOOP IT WILL BECOME 3) BECAUSE BEFORE ARE OTHER ELEMENTS OF THE PAGE THAT WE DON'T NEED
    df_pinnacle=pd.DataFrame(columns=['teams_pin', '1_pin', 'X_pin', '2_pin','goals_pin', 'over_pin', 'under_pin'])
    B=True
    while j<45:
        j+=1
        try:
            partido = pin.find_element(By.XPATH, '/html/body/div[2]/div/div[2]/main/div/div[2]/div[{}]'.format(j)).text.split('\n')
            teams = partido[0]+' '+partido[2]

            home_wins= partido[5]
            X = partido[6]
            away_wins = partido[7]

            goals = partido[12]
            under= partido[13]
            over = partido[15]
            if len(partido)==18:
                teams = partido[0]+' '+partido[3]

                home_wins= partido[6]
                X = partido[7]
                away_wins = partido[8]

                goals = partido[13]
                under= partido[14]
                over = partido[16]
            
            df_pinnacle.loc[len(df_pinnacle.index)] = [teams, home_wins, X, away_wins, goals,under, over]
            #print(teams, home_wins, X, away_wins, goals, over, under)
        except:
            pass
    #pin.quit()
    cols = ['1_pin', 'X_pin', '2_pin','goals_pin', 'over_pin', 'under_pin']
    
    for col in cols:
        for j in range(len(df_pinnacle.index)):
            if len(df_pinnacle[col].loc[j])>6:
                df_pinnacle[col].loc[j] = 1
    for col in cols:
            df_pinnacle[col]=df_pinnacle[col].astype('float64')
    
    return df_pinnacle

# MOZZARTBET
## Prematch

In [5]:
''' MOZZART PREMATCH Navigator Options'''
url_mozart_all = 'https://www.mozzartbet.com/en#/date/three_days'

options = Options()
options.add_argument('window-size=1920x1080') #Headless = True
options.headless = True #for not opening the navigator


moz_pre = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
moz_pre.get(url_mozart_all)

C:\Users\KNL\AppData\Local\Temp\ipykernel_28160\4171490382.py:9: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  moz_pre = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [ ]:
''' MOZZART PREMATCH FUNCTION ''' 
def mozzart_pre():
    df_moz_pre = pd.DataFrame(columns=['teams', '1_mz', 'X_mz', '2_mz', 'under 2.5_mz', 'over 2.5_mz'])
    element = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[4]')
    #time.sleep(10
    #print('scrolling start')

    for i in range(50):
        for j in range(40):
            try:
                element.location_once_scrolled_into_view
                element = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j))
                element2 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')
                
                teams = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[2]+' '+moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[3]

                mz_1 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[4]
                mz_X = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[5]
                mz_2 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[6]

                mz_under =  moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[10]
                mz_over =  moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[12]
                
                df_moz_pre.loc[len(df_moz_pre.index)] = [teams, mz_1, mz_X, mz_2, mz_under, mz_over]
                
                #print(teams, '       |',mz_1,'|', mz_X,'|', mz_2, '|', mz_under, '|', mz_over)
            except:
                pass
    return df_moz_pre

In [47]:
''' COLUMNS DATA TYPE and "-" replacing '''
df_mozzart_pre = df_mozzart_pre.replace('-', '1') # this is for columns containing missing odds, number 1 will make this bet not a surebet
columns = ['1_mz', 'X_mz', '2_mz', 'under 2.5_mz', 'over 2.5_mz']
for i in columns:
    df_mozzart_pre[i] = df_mozzart_pre[i].astype('float64')
df_mozzart_pre

,teams,1_mz,X_mz,2_mz,under 2.5_mz,over 2.5_mz,matches
0,Belgium Wales,1.42,4.70,9.00,2.08,1.75,"[(Belgium Wales, 100), (Bulgaria Gibraltar, 45)]"
1,Croatia Denmark,2.55,3.10,3.20,1.70,2.15,"[(Croatia Denmark, 100), (Serbia Sweden, 50)]"
2,France Austria,1.40,4.90,9.00,2.24,1.65,"[(France Austria, 100), (Armenia Ukraine, 59)]"
3,Poland Netherlands,3.60,3.50,2.15,1.95,1.85,"[(Poland Netherlands, 100), (Finland Romania, ..."
4,Scotland Ukraine,2.60,3.00,2.95,1.55,2.30,"[(Scotland Ukraine, 100), (Scotland Republic o..."
...,...,...,...,...,...,...,...
168,Queen of S. Edinburgh,1.55,4.10,4.90,2.15,1.55,"[(Serbia Sweden, 41), (Turkey Luxembourg, 41)]"
169,East Fife Stenhousemuir,2.40,3.60,2.50,1.80,1.80,"[(Croatia Denmark, 37), (France Austria, 37)]"
170,Stranraer Dumbarton,3.10,3.70,1.97,1.91,1.70,"[(Israel Albania, 48), (Armenia Ukraine, 45)]"
171,Fomat Martin Pohronie,7.00,4.40,1.40,2.70,1.40,"[(Georgia North Macedonia, 41), (Bosnia and He..."
173,Rudar V. Lendava,3.05,3.25,2.25,2.03,1.70,"[(Israel Albania, 40), (Bulgaria Gibraltar, 40)]"

# Live MOZZART

In [2]:
'''Navigator Options               MOZZART LIVE'''
options = Options()
options.headless = False #for not opening the navigator
options.add_argument('window-size=1920x1080') #Headless = True
url_mozart = 'https://www.mozzartbet.com/en#/live/sport/1'
moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
moz.get(url_mozart)
moz.set_window_size(1920, 1080)

C:\Users\KNL\AppData\Local\Temp\ipykernel_25116\1130887016.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [3]:
def mozzart():
    df_moz = pd.DataFrame(columns=['teams', '1_moz', 'X_moz', '2_moz','goals_mz', 'under_mz','over_mz'])
    for i in range(50): 
        try:
            partido = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[{}]'.format(i)).text.split('\n')

            if len(partido)==29:
                teams = partido[2]+' '+partido[3]
                moz_1 = partido[-19].replace('-','1')
                moz_X = partido[-18].replace('-','1')
                moz_2 = partido[-17].replace('-','1')

                goals_moz = partido[-10]
                under_moz = partido[-9].replace('-','1')
                over_moz = partido[-8].replace('-','1')
                df_moz.loc[len(df_moz.index)] = [teams, moz_1, moz_X, moz_2, goals_moz, under_moz, over_moz] 
                
            if len(partido)==27:
                teams = partido[2]+' '+partido[3]
                moz_1 = partido[8].replace('-','1')
                moz_X = partido[9].replace('-','1')
                moz_2 = partido[10].replace('-','1')

                goals_moz = partido[17]
                under_moz = partido[18].replace('-','1')
                over_moz = partido[19].replace('-','1')
                df_moz.loc[len(df_moz.index)] = [teams, moz_1, moz_X, moz_2, goals_moz, under_moz, over_moz] 
            





            #print(teams, '/', moz_1, moz_X, moz_2, '//', under_moz, goals_moz, over_moz)
        except:
            pass
    cols = [ '1_moz', 'X_moz', '2_moz', 'under_mz','over_mz']
    for col in cols:
        df_moz[col] = df_moz[col].astype('float64')
    return df_moz

In [4]:
mozzart()

,teams,1_moz,X_moz,2_moz,goals_mz,under_mz,over_mz
0,Andora Letonia,69.00,7.10,1.13,1.5,1.54,2.25
1,Lugo Oviedo,4.07,2.79,2.25,1.5,2.01,1.71
2,Moldavia Liechtenstein,1.95,2.01,19.10,0.5,2.11,1.62
3,Ursl Vise Waas. Beveren,3.92,3.43,1.91,2.5,1.62,2.06
4,Rentistas P. Colonia,2.94,2.94,2.55,1.5,2.16,1.57
5,Pk-35 Pargas Idrottsforening,1.81,3.28,5.75,1.5,2.40,1.44
6,Akron Tolyatti Fk Ufa,4.51,1.57,4.66,2.5,1.67,2.01
7,Shinnik Fk Rubin Kazan,1.39,3.68,11.80,1.5,2.16,1.62
8,Volgar A. Alania Vladikavkaz,4.82,3.11,1.99,1.5,1.91,1.71
9,Ud Cornella Cd Castellon,3.77,2.84,2.25,1.5,1.91,1.86
10,Tristan Suarez Gimnasia J,1.86,2.89,5.39,1.5,1.81,1.81
11,Bray Wanderers Waterford,69.00,21.00,1.02,4.5,1.49,2.30
12,Nk Rogaska Nd Beltinci,2.97,3.69,2.36,3.5,1.52,2.25
13,Nk Brinje Grosuplje Nk Fuzinar Ravne,4.85,3.77,1.67,5.5,1.52,2.25
14,Fc Forte Taganrog Fc Chayka Peschanokopskoye,6.13,1.81,2.84,0.5,2.01,1.67
15,Orenburg 2 Khimik Avgust Vurnari,2.70,1.91,5.68,0.5,2.21,1.57
16,Rotor Volgograd Dinamo Stavropol,1.62,3.48,6.13,1.5,2.30,1.49
17,Fc Tyumen Torpedo Miass,1.47,4.12,7.10,2.5,1.62,2.06
18,Cs Maritimo B Fc Alpendorada,3.28,3.19,2.21,2.5,1.91,1.71
19,Guarda Desportiva Fc Rebordosa Ac,1.86,3.33,4.21,2.5,2.06,1.62
20,Ad Castro Daire Ad Camacha,1.23,5.39,14.20,2.5,1.86,1.76
21,Lusitania Fc Salgueiros Porto,4.51,3.38,1.81,2.5,2.06,1.62
22,Gondomar Sc Gd Resende,1.37,4.21,9.07,4.5,1.52,2.25
23,Leca Fc Ad Machico,1.62,3.33,6.86,1.5,1.96,1.67
24,Su Sintrense Benfica Castelo Branco,4.31,3.09,1.96,1.5,2.21,1.54
25,Ud Santarem Arronches E Benfica,1.02,13.20,64.00,3.5,1.54,2.21
26,Grupo Sportivo De Loures Sociedade Uniao 1º De...,2.45,2.96,3.50,1.5,2.06,1.62
27,Sertanense Uniao Serra,1.16,6.86,18.60,2.5,2.35,1.47
28,Cd Alcains Mortagua,1.58,3.86,7.16,2.5,2.11,1.62
29,Coruchense Rio Maior Sc,2.21,2.74,3.92,1.5,1.86,1.76
30,Pero Pinheiro Ac Marinhense,1.42,4.07,7.84,2.5,1.76,1.86
31,Brito Sc Amarante,26.00,7.35,1.12,2.5,2.11,1.57
32,Sc Maria Fonte Braganca,1.62,3.23,7.35,1.5,1.91,1.76
33,Vianense Cd Vilar Perdizes,1.20,5.49,16.20,2.5,1.67,2.01
34,Atletico De Vila Mea Merelinense,4.36,3.23,1.86,2.5,1.81,1.81
35,Sao Martinho Ped. Salgadas,1.39,4.66,10.00,2.5,1.91,1.71
36,Hildesheim Bremer Sv 1906,34.00,9.31,1.08,2.5,2.50,1.44
37,Sariyer Serik Belediyespor,1.20,4.90,26.00,1.5,1.86,1.81
38,Ljungskile Sk Falkenbergs Ff,8.58,4.66,1.34,2.5,2.30,1.49
39,Asker Eidsvold Tf,1.02,14.20,49.00,4.5,1.76,1.86
40,Siegen Westfalia Rhynern,5.10,2.21,2.40,0.5,2.74,1.37
41,Bergisch Gl. Fc Ha1rth,1.10,6.86,54.00,1.5,1.91,1.76
42,Asc 09 Dortmund 1. Fc Gievenbeck,2.06,1.96,13.20,0.5,2.11,1.62
43,Sc Spelle Venhaus Mtv Gifhorn,1.00,22.00,196.00,3.5,2.40,1.49
44,Hannoverscher Sc Usi Lupo - Martini,32.00,6.13,1.14,1.5,2.45,1.47
45,Fortuna Koln B Sve Hohkeppel,1.81,3.43,4.26,2.5,2.16,1.57
46,Asko Kottmannsdorf Ask Klagenfurt,19.10,4.90,1.23,1.5,2.65,1.42
47,Onsala Bk Assyriska Bk,1.03,12.70,54.00,3.5,1.71,1.96
48,Tsv Steinbach Ii Baunatal,18.10,4.85,1.24,7.5,2.74,1.39

# ---------------------------------------------------------
# SoccerBET

## LIVE

In [5]:
'''                                  SOCCERBET NAVIGATOR TO THE BACKGROUND'''


url_soc = 'https://soccerbet.rs/#live/overview'

#changing chromedriver default options
options = Options()
options.headless = True #for not opening the navigator
options.add_argument('window-size=1920x1080') #Headless = True
soc = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
soc.get(url_soc)
cancel = soc.find_element(By.XPATH, '//*[@id="promotionPopupModal"]/div/div/div/div/input')
cancel.click()

C:\Users\KNL\AppData\Local\Temp\ipykernel_25116\509003485.py:10: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  soc = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [6]:
''' SOCCERBET FUNCTION'''
def soccerbet():
    df_socc = pd.DataFrame(columns=['teams', '1_socc', 'X_socc', '2_socc', 'goals_socc', 'under_socc', 'over_socc'])
    for i in range(60):
        try:
            element = soc.find_element(By.XPATH, f'//*[@id="result-tables"]/div[2]/div[1]/table/tbody/tr[{i}]').text.split('\n')
            teams = element[1][4:].replace(':','')
            teams = re.sub('\d+','',teams)

            socc_1 = element[2].replace('-', '1')
            socc_X = element[3].replace('-', '1')
            socc_2 = element[4].replace('-', '1')

            goals_socc= element[10][:3].replace('-', '1')
            under_socc= element[8].replace('-', '1')
            over_socc=element[9].replace('-', '1')

            df_socc.loc[len(df_socc.index)] = [teams, socc_1, socc_X,socc_2, goals_socc, under_socc, over_socc]

            #print(teams, socc_1, socc_X, socc_2, '|',under_socc, over_socc)

            cols = ['1_socc', 'X_socc', '2_socc', 'goals_socc', 'under_socc',
       'over_socc']
            for c in cols:
                df_socc[c] = df_socc[c].astype('float64')
        except:
            pass
    return df_socc

In [9]:
soccerbet()

,teams,1_socc,X_socc,2_socc,goals_socc,under_socc,over_socc
0,Andorra Latvia,63.50,7.50,1.13,1.5,1.60,2.40
1,Moldova Liechtenstein,2.05,2.05,21.00,0.5,2.10,1.70
2,TN Stars Ekwendeni Hammers,99.00,9.25,1.08,1.5,1.23,3.25
3,-Z Aarhus W Brondby W,99.00,7.50,1.13,5.5,1.27,3.40
4,Amiens U Valenciennes U,3.25,1.85,3.95,2.5,2.05,1.60
5,Drancy U Montfermeil U,30.50,9.00,1.01,2.5,1.85,1.75
6,Paris U Dijon U,1.08,7.50,48.00,1.5,2.05,1.60
7,Lens U Gonfreville U,1.01,9.25,34.50,2.5,1.90,1.70
8,SC Air Bel U Colomiers U,1.38,3.70,12.50,1.5,1.85,1.75
9,Torcy U Auxerre U,49.50,11.00,1.03,2.5,1.80,1.80
10,Orleans U Dunkerque U,1.04,11.00,47.00,2.5,1.95,1.68
11,Shinnik Rubin,1.45,3.80,12.00,1.5,2.10,1.68
12,Akron Togliatti Ufa,4.65,1.60,4.80,2.5,1.68,2.05
13,Sariyer Serik Bld.,1.25,5.10,24.50,1.5,1.85,1.85
14,S Hildesheim Bremer SV,30.50,11.00,1.01,3.5,2.30,1.55
15,S Gefle IF IF Karlstad,1.08,6.60,38.50,3.5,2.10,1.58
16,S Stockholm Intern. Umea,3.05,1.85,5.80,2.5,2.05,1.70
17,SS IFK Stocksund IFK Osteraakers,13.50,4.00,1.40,3.5,2.35,1.53
18,SS Jarfalla Kvarnsvedens IK,1.00,1.00,1.00,4.5,2.60,1.43
19,-Z AIK W Eskilstuna W,66.50,22.50,1.00,2.5,1.90,1.85
20,-Z Brighton W Reading W,1.23,5.40,29.50,1.5,2.10,1.65
21,/ Lyn Stabaek II,1.00,19.50,99.00,4.5,2.25,1.58
22,Magara YB Vital O,78.50,9.25,1.08,3.5,2.00,1.68
23,Al Yarmouk Al Baqaa,1.27,4.75,23.00,3.5,1.85,1.85
24,Al Karmel Sama Al Sarhan,37.00,6.00,1.18,5.5,2.00,1.70
25,Emirates Hatta,2.25,2.60,4.55,0.5,3.40,1.27
26,Al Tawon Al Dhaid,2.80,2.85,2.95,2.5,4.70,1.18
27,Dibba Al Hisn Fursan Hispania,1.18,6.80,24.50,1.5,4.35,1.18
28,Al Jazira Al Hamra Al Arabi Umm Al Quwain,1.60,3.60,6.70,1.5,3.85,1.23

# --------------------------------------------------

# ADMIRAL

## LIVE

In [7]:
'''Navigator Options               ADMIRAL LIVE'''
url_adm = 'https://admiralbet.rs/sport-live'
options = Options()
options.headless = True #for not opening the navigator


adm = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
adm.get(url_adm)
adm.set_window_size(1920, 1080)
time.sleep(4)

adm.switch_to.frame(adm.find_element(By.XPATH, '//*[@id="sportLiveIframe"]'))
fudbal = adm.find_element(By.XPATH, '/html/body/app-root/app-betting-live/div[2]/section[2]/div/app-sport-groups-container/app-sport-group[1]/section/div')
fudbal.click()

C:\Users\KNL\AppData\Local\Temp\ipykernel_25116\2400326153.py:7: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  adm = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [52]:
def admiral():
    
    df_adm = pd.DataFrame(columns=['teams', '1_adm', 'X_adm', '2_adm', 'goals_adm', 'under_adm', 'over_adm'])
    for k in range(40):
        for j in range(6):
            try:
                elemento = adm.find_element(By.XPATH, f'/html/body/app-root/app-betting-live/div[2]/section[2]/div/app-sport-groups-container/app-sport-group[1]/section/app-competition-group[{k}]/section/div[2]/app-event-live[{j}]').text.split('\n')
                
                teams = elemento[2]+' '+ elemento[3]

                adm_1 = elemento[8].replace('-','1')
                adm_X = elemento[9].replace('-','1')
                adm_2 = elemento[10].replace('-','1')
                
                goals_adm = elemento[20].replace('-','0')
                
                under = elemento[19].replace('-','1')
                over = elemento[21].replace('-','1')
                df_adm.loc[len(df_adm.index)] = [teams, adm_1, adm_X, adm_2, goals_adm, under, over]
                #print(teams,'|', adm_1, adm_X, adm_2,'    |  ', goals_adm, under ,over)
            except:
                pass
    cols = ['1_adm', 'X_adm', '2_adm',  'under_adm','goals_adm','over_adm']
    for c in cols:
        df_adm[c]= df_adm[c].astype('float64')

    df_adm = df_adm[df_adm.goals_adm<5]
    return df_adm

In [54]:
admiral()

,teams,1_adm,X_adm,2_adm,goals_adm,under_adm,over_adm
0,Lugo Real Oviedo,6.25,1.60,3.65,0.5,1.75,2.05
1,Cornella Castellon,9.75,1.25,5.50,0.5,1.27,3.35
2,Pontevedra Linense,2.00,2.60,5.50,1.5,1.60,2.20
3,Gondomar Gd Resende,1.00,1.00,1.00,0.0,1.00,1.00
4,Leca AD Machico,1.00,11.50,150.00,3.5,1.70,2.00
...,...,...,...,...,...,...,...
62,Utebo Izarra,2.90,2.10,3.95,1.5,1.37,2.80
63,Marino De Luanco Zamora,3.40,2.15,3.10,1.5,1.33,2.90
64,Alfaro Tudelano,1.42,3.80,8.40,2.5,1.50,2.35
65,CF Pozuelo de Alarcon W Futbolellas Cff W,1.95,2.85,4.80,2.5,1.22,3.75
66,Murcia Feminas W Discobolo La Torre AC W,1.27,5.90,9.00,4.5,1.85,1.85

# FuzzMerge
###                         Pinnacle / Mozzart

In [50]:
''' complete trial '''
s=0
while s<20:
    s+=1
    df_pin = pinnacle()
    df_moz = mozzart()


    teams_moz = df_moz.teams.tolist()
    teams_pin= df_pin.teams_pin.tolist()
    mat1 = []
    mat2 = []
    p=[]
    df_pin_moz = pd.DataFrame(columns=['teams_pin', 'teams', 'score', '1_pin', 'X_pin', '2_pin','goals_pin', 'over_pin','under_pin'])




    df_pin[['teams_matched', 'score_moz']] = df_pin.teams_pin.apply(lambda x: process.extractOne(x, teams_moz, scorer=fuzz.token_sort_ratio)).apply(pd.Series)
    df_pin = df_pin[df_pin.score_moz>65]


            
    df = pd.merge(df_pin, df_moz, left_on='teams_matched', right_on='teams')
    df = df[['teams_pin','teams_matched', '1_pin','1_moz', 'X_pin','X_moz', '2_pin','2_moz', 'goals_pin', 'over_pin','under_pin', 'goals_mz', 'under_mz', 'over_mz']]
    #creating  surebet columns
    df['Over_MOZ/ Under_Pinnacle'] = df.over_mz**-1+df.under_pin**-1
    df['Over_Pinnacle/ Under_Mozzart'] = df.over_pin**-1+df.under_mz**-1

    #Creating dataframes to store those matches in surebets
    df_surebet = df[df['Over_MOZ/ Under_Pinnacle']<1].sort_values('Over_MOZ/ Under_Pinnacle')[['teams_pin','over_mz', 'under_pin', 'Over_MOZ/ Under_Pinnacle', 'goals_mz', 'goals_pin']]
    df_surebet2  =df [df['Over_Pinnacle/ Under_Mozzart']<1].sort_values('Over_Pinnacle/ Under_Mozzart')[['teams_pin','over_pin', 'under_mz', 'Over_Pinnacle/ Under_Mozzart', 'goals_pin','goals_mz']]



    clear_output()
    display('               under pinnacle / over mozzart ',df_surebet,'               Over Pinnacle / Under Mozzart', df_surebet2,'               Matches in both sites',df[['teams_pin','teams_matched']])

'               under pinnacle / over mozzart '

Empty DataFrame
Columns: [teams_pin, over_mz, under_pin, Over_MOZ/ Under_Pinnacle, goals_mz, goals_pin]
Index: []

'               Over Pinnacle / Under Mozzart'

Empty DataFrame
Columns: [teams_pin, over_pin, under_mz, Over_Pinnacle/ Under_Mozzart, goals_pin, goals_mz]
Index: []

'               Matches in both sites'

                               teams_pin             teams_matched
0  Boyaca Patriotas CD Alianza Petrolera  Patriotas  Al. Petrolera
1                Titanes Fc Angostura FC  Titanes Fc  Angostura Fc

## Soccerbet / Mozzartbet

In [13]:
''' SOCCERBET VS MOZZART'''
for j in range(5):
    df_soc = soccerbet()
    df_moz = mozzart()

    teams_soc = df_soc.teams.tolist()
    teams_moz = df_moz.teams.tolist()


    #HERE I CREATE A NEW COLUMN
    df_soc[['teams_matched', 'score_moz']] = df_soc.teams.apply(lambda x:process.extractOne(x, teams_moz, scorer=fuzz.token_sort_ratio)).apply(pd.Series)
    df_soc = df_soc[df_soc.score_moz>59]

    ''' MERGING TWO DATAFRAMES'''
    
    df_soc_moz = pd.merge(df_moz, df_soc, left_on='teams',right_on='teams_matched',  how='right' )
    df_soc_moz = df_soc_moz[['teams_x' , 'goals_socc', 'goals_mz' , 'over_mz' , 'under_socc',  'over_socc', 'under_mz' ]]
    
    ''' CALCULATING SUREBETS FOR UNDER/OVER GOALS '''
    df_soc_moz['OVER_MOZART / UNDER SOCC'] = df_soc_moz.over_mz**-1+df_soc_moz.under_socc**-1
    df_soc_moz['OVER SOCC / UNDER_MOZART'] = df_soc_moz.over_socc**-1 + df_soc_moz.under_mz**-1
    
    df1 = df_soc_moz.sort_values('OVER_MOZART / UNDER SOCC')[['teams_x', 'goals_socc', 'goals_mz' , 'over_mz', 'under_socc', 'OVER_MOZART / UNDER SOCC']]
    df2 = df_soc_moz.sort_values('OVER SOCC / UNDER_MOZART')[['teams_x', 'goals_socc', 'goals_mz' , 'over_socc', 'under_mz', 'OVER SOCC / UNDER_MOZART']]
    #time.sleep(0.5)
    clear_output()
    display(df1, df2)
    print(j)

,teams_x,goals_socc,goals_mz,over_mz,under_socc,OVER_MOZART / UNDER SOCC
11,Brito Sc Amarante,2.5,3.5,2.74,2.75,0.728600
2,Ursl Vise Waas. Beveren,1.5,2.5,2.35,3.15,0.742992
6,Ljungskile Sk Falkenbergs Ff,2.5,3.5,2.16,3.55,0.744653
15,Cd Alcains Mortagua,2.5,3.5,2.70,2.65,0.747729
3,Bray Wanderers Waterford,2.5,3.5,2.21,3.35,0.750996
7,Rentistas P. Colonia,1.5,2.5,2.21,3.30,0.755519
12,Lusitania Fc Salgueiros Porto,1.5,2.5,2.11,3.50,0.759648
5,Asker Eidsvold Tf,3.5,4.5,1.81,4.30,0.785044
9,Vianense Cd Vilar Perdizes,1.5,1.5,1.91,2.90,0.868388
4,Ud Cornella Cd Castellon,0.5,0.5,1.62,2.20,1.071829
10,Sc Maria Fonte Braganca,0.5,0.5,1.52,2.30,1.092677
8,Sao Martinho Ped. Salgadas,1.5,1.5,1.47,2.40,1.096939
16,Coruchense Rio Maior Sc,0.5,0.5,1.47,2.40,1.096939
13,Ad Castro Daire Ad Camacha,2.5,2.5,1.44,2.45,1.102608
1,Tristan Suarez Gimnasia J,0.5,0.5,1.39,2.60,1.104040
0,Volgar A. Alania Vladikavkaz,0.5,0.5,1.39,2.60,1.104040
14,Pero Pinheiro Ac Marinhense,1.5,1.5,1.49,2.30,1.105924

,teams_x,goals_socc,goals_mz,over_socc,under_mz,OVER SOCC / UNDER_MOZART
0,Volgar A. Alania Vladikavkaz,0.5,0.5,1.45,2.70,1.060026
8,Sao Martinho Ped. Salgadas,1.5,1.5,1.53,2.45,1.061758
1,Tristan Suarez Gimnasia J,0.5,0.5,1.43,2.74,1.064264
13,Ad Castro Daire Ad Camacha,2.5,2.5,1.50,2.50,1.066667
4,Ud Cornella Cd Castellon,0.5,0.5,1.60,2.25,1.069444
14,Pero Pinheiro Ac Marinhense,1.5,1.5,1.55,2.35,1.070693
16,Coruchense Rio Maior Sc,0.5,0.5,1.50,2.45,1.074830
10,Sc Maria Fonte Braganca,0.5,0.5,1.55,2.30,1.079944
9,Vianense Cd Vilar Perdizes,1.5,1.5,1.35,1.71,1.325536
5,Asker Eidsvold Tf,3.5,4.5,1.18,1.81,1.399944
7,Rentistas P. Colonia,1.5,2.5,1.30,1.54,1.418581
15,Cd Alcains Mortagua,2.5,3.5,1.43,1.37,1.429228
3,Bray Wanderers Waterford,2.5,3.5,1.27,1.54,1.436752
6,Ljungskile Sk Falkenbergs Ff,2.5,3.5,1.25,1.57,1.436943
12,Lusitania Fc Salgueiros Porto,1.5,2.5,1.25,1.57,1.436943
2,Ursl Vise Waas. Beveren,1.5,2.5,1.30,1.49,1.440372
11,Brito Sc Amarante,2.5,3.5,1.40,1.34,1.460554

4

## Admiral / MozzartBET

In [63]:
''' ADMIRAL VS MOZZART''' 
for j in range(5):
    df_adm = admiral()
    df_moz  = mozzart()

    teams_adm = df_adm.teams.tolist()
    teams_moz = df_moz.teams.tolist()

    df_adm[['teams_foreign', 'score']] = df_adm.teams.apply(lambda x:process.extractOne(x, teams_moz, scorer=fuzz.token_sort_ratio)).apply(pd.Series)
    df_adm = df_adm[df_adm['score']>59]

    #Merging dataframes 
    df_adm_moz = pd.merge(df_adm, df_moz, left_on='teams_foreign',right_on='teams', how='left')
    df_adm_moz = df_adm_moz[['teams_x','goals_adm','goals_mz', 'under_adm', 'over_mz', 'over_adm',   'under_mz',]]

    df_adm_moz['ADM / moz'] = df_adm_moz.over_adm**-1+df_adm_moz.under_mz**-1
    df_adm_moz['MOZ / adm'] = df_adm_moz.over_mz**-1 +df_adm_moz.under_adm**-1

    df1= df_adm_moz[['teams_x', 'goals_adm', 'goals_mz', 'over_adm', 'under_mz' , 'ADM / moz']].sort_values('ADM / moz')
    df2= df_adm_moz[['teams_x', 'goals_adm', 'goals_mz', 'over_mz', 'under_adm', 'MOZ / adm']].sort_values('MOZ / adm')
    clear_output()
    display(df1, df2)

,teams_x,goals_adm,goals_mz,over_adm,under_mz,ADM / moz
15,Zapy FK Teplice B,1.5,0.5,2.90,2.79,0.703251
27,Asante Kotoko Hearts of Oak,1.5,0.5,3.20,2.55,0.704657
24,Bibiani Gold Stars FC Bechem United,2.5,1.5,2.90,2.74,0.709791
14,Sokol Hostoun Kraluv Dvur,3.5,2.5,3.20,2.45,0.720663
19,Deportes Iquique U. De Concepcion,3.5,2.5,2.85,2.16,0.813840
20,Independiente Juniors CDA Santo Domingo,2.5,1.5,2.75,2.21,0.816125
30,Barco Csd Arzua,3.5,2.5,3.00,2.06,0.818770
34,Sevilla C Conil,2.5,1.5,3.30,1.91,0.826591
16,Hercules OLS Oulu,3.5,2.5,3.60,1.81,0.830264
29,UD Paiosaco CD Estradense,3.5,2.5,3.00,2.01,0.830846
1,Pontevedra Linense,1.5,1.5,2.50,1.47,1.080272
33,Leioa Anaitasuna,2.5,2.5,1.95,1.76,1.081002
18,Utebo Izarra,0.5,0.5,1.52,2.35,1.083427
0,Lugo Real Oviedo,0.5,0.5,3.60,1.24,1.084229
9,Lillestrom SK 2 Senja,3.5,3.5,2.05,1.67,1.086607
31,Union Club Ceares Condal Club,3.5,3.5,2.05,1.67,1.086607
21,Al Shabab Al Sahel,1.5,1.5,2.05,1.67,1.086607
7,Chelsea W Manchester City W,2.5,2.5,1.90,1.76,1.094498
17,Palencia CA Bergantinos,3.5,3.5,2.35,1.49,1.096673
11,Dynamo Makhachkala Rodina Moscow,1.5,1.5,2.65,1.39,1.096783
28,Aduana Samartex,3.5,3.5,2.15,1.57,1.102059
26,Karela United Dreams,3.5,3.5,2.60,1.39,1.104040
25,Kotoku Royals Nsoatreman FC,1.5,1.5,2.35,1.47,1.105804
23,Croatia U20 Albania U20,0.0,4.5,1.00,2.55,1.392157
32,Llanera CD Lealtad de Villaviciosa,0.0,-,1.00,1.00,2.000000
2,Guarda Desportiva FC Rebordosa AC,0.0,4.5,1.00,1.00,2.000000
3,Vila Mea Merelinense,0.0,-,1.00,1.00,2.000000
12,Tyumen Torpedo Miass,0.0,-,1.00,1.00,2.000000
13,Club Atletico Rentistas Plaza Colonia,0.0,-,1.00,1.00,2.000000
22,Club Omnisports de Korhogo SC Gagnoa,0.0,-,1.00,1.00,2.000000
6,Tristan Suarez Gimnasia Jujuy,0.0,4.5,1.00,1.00,2.000000
8,Asker Eidsvold,0.0,-,1.00,1.00,2.000000
10,Club Sportivo Luqueno Atletico Colegiales,0.0,1.5,1.00,1.00,2.000000
4,Lusitania Salgueiros Porto,0.0,1.5,1.00,1.00,2.000000
5,Castro Daire Camacha,0.0,-,1.00,1.00,2.000000

,teams_x,goals_adm,goals_mz,over_mz,under_adm,MOZ / adm
0,Lugo Real Oviedo,0.5,0.5,3.72,1.25,1.068817
1,Pontevedra Linense,1.5,1.5,2.55,1.45,1.081812
31,Union Club Ceares Condal Club,3.5,3.5,2.01,1.70,1.085748
21,Al Shabab Al Sahel,1.5,1.5,2.01,1.70,1.085748
9,Lillestrom SK 2 Senja,3.5,3.5,2.01,1.70,1.085748
10,Club Sportivo Luqueno Atletico Colegiales,0.0,1.5,11.30,1.00,1.088496
26,Karela United Dreams,3.5,3.5,2.60,1.42,1.088841
11,Dynamo Makhachkala Rodina Moscow,1.5,1.5,2.60,1.42,1.088841
25,Kotoku Royals Nsoatreman FC,1.5,1.5,2.35,1.50,1.092199
17,Palencia CA Bergantinos,3.5,3.5,2.35,1.50,1.092199
18,Utebo Izarra,0.5,0.5,1.52,2.30,1.092677
33,Leioa Anaitasuna,2.5,2.5,1.86,1.80,1.093190
28,Aduana Samartex,3.5,3.5,2.11,1.60,1.098934
7,Chelsea W Manchester City W,2.5,2.5,1.86,1.75,1.109063
6,Tristan Suarez Gimnasia Jujuy,0.0,4.5,6.37,1.00,1.156986
4,Lusitania Salgueiros Porto,0.0,1.5,6.13,1.00,1.163132
2,Guarda Desportiva FC Rebordosa AC,0.0,4.5,5.00,1.00,1.200000
29,UD Paiosaco CD Estradense,3.5,2.5,1.67,1.35,1.339543
34,Sevilla C Conil,2.5,1.5,1.71,1.30,1.354026
16,Hercules OLS Oulu,3.5,2.5,1.86,1.22,1.357307
30,Barco Csd Arzua,3.5,2.5,1.62,1.35,1.358025
20,Independiente Juniors CDA Santo Domingo,2.5,1.5,1.54,1.40,1.363636
19,Deportes Iquique U. De Concepcion,3.5,2.5,1.57,1.37,1.366870
14,Sokol Hostoun Kraluv Dvur,3.5,2.5,1.47,1.30,1.449503
15,Zapy FK Teplice B,1.5,0.5,1.37,1.37,1.459854
24,Bibiani Gold Stars FC Bechem United,2.5,1.5,1.39,1.35,1.460165
27,Asante Kotoko Hearts of Oak,1.5,0.5,1.44,1.30,1.463675
23,Croatia U20 Albania U20,0.0,4.5,1.44,1.00,1.694444
5,Castro Daire Camacha,0.0,-,1.00,1.00,2.000000
8,Asker Eidsvold,0.0,-,1.00,1.00,2.000000
3,Vila Mea Merelinense,0.0,-,1.00,1.00,2.000000
13,Club Atletico Rentistas Plaza Colonia,0.0,-,1.00,1.00,2.000000
12,Tyumen Torpedo Miass,0.0,-,1.00,1.00,2.000000
32,Llanera CD Lealtad de Villaviciosa,0.0,-,1.00,1.00,2.000000
22,Club Omnisports de Korhogo SC Gagnoa,0.0,-,1.00,1.00,2.000000

## Admiral / Soccerbet

In [64]:
''' ADMIRAL VS SOCCERBET '''
for j in range(5):
    df_soc = soccerbet()
    df_adm = admiral()

    teams_soc = df_soc.teams.tolist()
    teams_adm = df_adm.teams.tolist()
    #Adding one columns with foreing teams
    df_soc[['teams_matched', 'score']] = df_soc.teams.apply(lambda x:process.extractOne(x, teams_adm, scorer=fuzz.token_sort_ratio)).apply(pd.Series)
    df_soc= df_soc[df_soc.score>59]
    #MERGE through teams_matched
    df_soc_adm = pd.merge(df_soc, df_adm, left_on='teams_matched', right_on='teams' , how='left')
    df_soc_adm = df_soc_adm[['teams_x',  'goals_socc', 'under_socc','over_socc','goals_adm', 'under_adm', 'over_adm']]
    #Calculating new columns
    df_soc_adm['SOC/adm']=df_soc_adm.over_socc**-1+df_soc_adm.under_adm**-1
    df_soc_adm['ADM/soc']=df_soc_adm.over_adm**-1+df_soc_adm.under_socc**-1

    df1 = df_soc_adm[['teams_x',  'goals_socc','goals_adm', 'over_socc', 'under_adm', 'SOC/adm']].sort_values('SOC/adm')
    df2 = df_soc_adm[['teams_x',  'goals_socc','goals_adm', 'over_adm', 'under_socc', 'ADM/soc']].sort_values('ADM/soc')
    clear_output()
    display(df1, df2)

,teams_x,goals_socc,goals_adm,over_socc,under_adm,SOC/adm
15,Utebo Izarra,0.5,0.5,1.55,2.35,1.070693
4,Lugo Real Oviedo,0.5,0.5,3.90,1.20,1.089744
5,Croatia U Albania U,4.5,4.5,1.48,2.35,1.101208
3,Pero Pinheiro Marinhense,1.5,0.0,4.60,1.00,1.217391
1,Rentistas Plaza Colonia,1.5,0.0,4.20,1.00,1.238095
2,Lusitania Salgueiros,1.5,0.0,4.05,1.00,1.246914
18,/ Lillestrom II Senja,2.5,3.5,1.45,1.65,1.295716
6,-Z Chelsea W Man. City W,1.5,2.5,1.20,1.80,1.388889
14,Palencia Cristo Atl. Bergantinos,2.5,3.5,1.33,1.50,1.418546
9,Praiense Imortal,0.5,1.5,1.40,1.40,1.428571
8,Beira Mar Valadares Gaia,0.5,1.5,1.38,1.42,1.428863
10,Dynamo Makhachkala Rodina Moscow,0.5,1.5,1.38,1.42,1.428863
12,/ Pontevedra Linense,0.5,1.5,1.35,1.45,1.430396
13,Marino L. Zamora,0.5,1.5,1.45,1.27,1.477057
11,-Z Villarreal W Barcelona W,2.5,4.5,1.33,1.30,1.521110
17,Iquique Uni. Concepcion,1.5,3.5,1.15,1.35,1.610306
7,C JS Hercules OLS,1.5,3.5,1.23,1.22,1.632680
19,CO Korhogo Sporting Gagnoa,1.5,0.0,1.43,1.00,1.699301
16,F Al Shabab Kuwait Al Sahel,0.5,0.0,1.25,1.00,1.800000
20,Independiente Juniors Atl.Santo Domingo,0.5,0.0,1.15,1.00,1.869565
0,Tristan Suarez Gimnasia Jujuy,4.5,0.0,1.00,1.00,2.000000

,teams_x,goals_socc,goals_adm,over_adm,under_socc,ADM/soc
7,C JS Hercules OLS,1.5,3.5,3.60,3.95,0.530942
17,Iquique Uni. Concepcion,1.5,3.5,2.95,5.20,0.531291
11,-Z Villarreal W Barcelona W,2.5,4.5,3.20,3.20,0.625000
13,Marino L. Zamora,0.5,1.5,3.35,2.50,0.698507
12,/ Pontevedra Linense,0.5,1.5,2.50,3.00,0.733333
9,Praiense Imortal,0.5,1.5,2.70,2.75,0.734007
10,Dynamo Makhachkala Rodina Moscow,0.5,1.5,2.65,2.80,0.734501
8,Beira Mar Valadares Gaia,0.5,1.5,2.60,2.80,0.741758
14,Palencia Cristo Atl. Bergantinos,2.5,3.5,2.35,3.10,0.748113
6,-Z Chelsea W Man. City W,1.5,2.5,1.90,4.15,0.767280
18,/ Lillestrom II Senja,2.5,3.5,2.10,2.55,0.868347
4,Lugo Real Oviedo,0.5,0.5,4.00,1.23,1.063008
5,Croatia U Albania U,4.5,4.5,1.50,2.50,1.066667
15,Utebo Izarra,0.5,0.5,1.52,2.30,1.092677
20,Independiente Juniors Atl.Santo Domingo,0.5,0.0,1.00,5.20,1.192308
16,F Al Shabab Kuwait Al Sahel,0.5,0.0,1.00,3.50,1.285714
19,CO Korhogo Sporting Gagnoa,1.5,0.0,1.00,2.60,1.384615
2,Lusitania Salgueiros,1.5,0.0,1.00,1.15,1.869565
1,Rentistas Plaza Colonia,1.5,0.0,1.00,1.15,1.869565
3,Pero Pinheiro Marinhense,1.5,0.0,1.00,1.13,1.884956
0,Tristan Suarez Gimnasia Jujuy,4.5,0.0,1.00,1.00,2.000000