In [2]:
''' LIBRARIES '''
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains

import time
from IPython.display import clear_output


import pandas as pd
import numpy as np

In [10]:
'''Navigator Options               MOZZART LIVE'''
options = Options()
options.headless = False #for not opening the navigator
options.add_argument('window-size=1920x1080') #Headless = True
url_mozart = 'https://www.mozzartbet.com/en#/live/sport/1'
moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
moz.get(url_mozart)

C:\Users\KNL\AppData\Local\Temp\ipykernel_22808\2346320359.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [6]:
'''                                     MOZZART LIVE FUNCTION '''
def mozzart():
    #options = Options()
    #options.headless = True #for not opening the navigator
    #options.add_argument('window-size=1920x1080') #Headless = True
    #url_mozart = 'https://www.mozzartbet.com/en#/live/sport/1'
    #moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
    #moz.get(url_mozart)
    i=0
    df_mozart = pd.DataFrame(columns=['teams', 'final_result', 'over_under']) 
    while i<30:
        
        i=i+1
        try:
            partido = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[{}]'.format(i)).text.split('\n')
            if len(partido)==29:
                teams=partido[2]+'  '+partido[3]
                final_result= partido[10:13]
                over_under=partido[19:22]
                df_mozart.loc[len(df_mozart.index)] = [teams, final_result, over_under] 
                
                
                #print(teams, final_result, over_under)
                
            if len(partido)==27:
                teams=partido[2]+'  '+partido[3]
                final_result= partido[8:11]
                over_under=partido[17:20]
                df_mozart.loc[len(df_mozart.index)] = [teams, final_result, over_under] 
                
                #print(teams, final_result, over_under)

        except:
            break
    
    
    #moz.quit()
    
    '''
    TRANSFORMING AND REPLACING DATA
    '''
    # Spliting the numbers

    df_mozart[['1_moz', 'X_moz', '2_moz']] = df_mozart.final_result.apply(lambda x: pd.Series(str(x).split(',')))
    df_mozart[['goals_mz', 'under_mz','over_mz']] = df_mozart.over_under.apply(lambda x: pd.Series(str(x).split(',')))

    #Deleting some characters

    cols = ['1_moz', 'X_moz', '2_moz','teams','goals_mz', 'under_mz','over_mz']
    for col in cols:
        df_mozart[col]=df_mozart[col].apply(lambda x: x.replace("'",""))
        df_mozart[col]=df_mozart[col].apply(lambda x: x.replace("[",""))
        df_mozart[col]=df_mozart[col].apply(lambda x: x.replace("]",""))
        df_mozart[col]=df_mozart[col].apply(lambda x: x.replace("-","1"))
        
    col2 = cols = ['1_moz', 'X_moz', '2_moz','goals_mz', 'under_mz','over_mz']
    for col in col2:    
        df_mozart[col]= df_mozart[col].astype('float64')

    df_mozart.drop(columns=['final_result', 'over_under'], inplace=True)

    
    return df_mozart

In [18]:
partido = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[2]').text.split('\n')
for idx, c in enumerate(partido):
    print(idx, c, len(partido)-idx)
len(partido)

0 64:11 23
1 JP 19.459,20 22
2 Burgos Cf 21
3 Levante 20
4 0 19
5 0 18
6 0 17
7 0 16
8 0 15
9 0 14
10 5.39 13
11 1.93 12
12 2.89 11
13 4.07 10
14 2.21 9
15 2.50 8
16 5.39 7
17 1.93 6
18 2.89 5
19 0.5 4
20 2.21 3
21 1.62 2
22 119 1

23

In [25]:
def mozzart():
    df_moz = pd.DataFrame(columns=['teams', '1_moz', 'X_moz', '2_moz','goals_mz', 'under_mz','over_mz'])
    for i in range(60): 
        try:
            partido = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[{}]'.format(i)).text.split('\n')

            teams = partido[2]+' '+partido[3]

            moz_1 = partido[-13].replace('-','1')
            moz_X = partido[-12].replace('-','1')
            moz_2 = partido[-11].replace('-','1')

            goals_moz = partido[-4]
            under_moz = partido[-3].replace('-','1')
            over_moz = partido[-2].replace('-','1')
            df_moz.loc[len(df_moz.index)] = [teams, moz_1, moz_X, moz_2, goals_moz, under_moz, over_moz] 
            #print(teams, '/', moz_1, moz_X, moz_2, '//', under_moz, goals_moz, over_moz)
        except:
            pass
    cols = [ '1_moz', 'X_moz', '2_moz', 'under_mz','over_mz']
    for col in cols:
        df_moz[col] = df_moz[col].astype('float64')
    return df_moz

,teams,1_moz,X_moz,2_moz,goals_mz,under_mz,over_mz
0,Andora Letonia,5.24,2.43,2.33,1.5,1.44,2.45
1,Burgos Cf Levante,5.68,1.78,3.19,0.5,1.96,1.81
2,Moldavia Liechtenstein,1.32,4.21,17.20,1.5,2.11,1.62
3,Chengdu Rongcheng Henan Jianye,4.36,1.56,5.29,0.5,1.62,2.11
4,Krasnodar B Neftekhimik,3.77,1.62,5.39,0.5,1.71,1.96
5,Akron Tolyatti Fk Ufa,2.79,2.60,3.04,1.5,1.76,1.91
6,Shinnik Fk Rubin Kazan,3.30,2.97,2.56,1.5,2.11,1.57
7,Fc Forte Taganrog Fc Chayka Peschanokopskoye,4.88,3.13,1.98,1.5,2.25,1.52
8,Orenburg 2 Khimik Avgust Vurnari,2.05,3.05,4.68,1.5,2.35,1.47
9,Teutonia Ottensen 1905 Rehden,5.00,2.16,2.40,3.5,1.37,2.70
10,Kieler Sv Holstein B Kickers Emden,1.00,147.00,294.00,5.5,2.50,1.44
11,Hildesheim Bremer Sv 1906,2.70,3.53,2.40,3.5,1.71,1.91
12,Sivas Dort Afjet Afyonspor,31.00,5.19,1.18,1.5,1.71,1.96
13,Hekimoglu Trabzon Karacabey Belediyespor As,3.58,1.62,5.49,0.5,1.76,1.91
14,Zonguldak Iskenderun Fk,1.62,3.48,6.37,2.5,1.54,2.21
15,Sariyer Serik Belediyespor,1.42,4.17,8.33,2.5,1.91,1.71
16,Siegen Westfalia Rhynern,4.61,3.58,1.71,2.5,1.62,2.11
17,Bergisch Gl. Fc Ha1rth,1.71,3.19,5.49,1.5,2.21,1.54
18,Asc 09 Dortmund 1. Fc Gievenbeck,1.57,3.87,5.59,2.5,1.67,1.96
19,Sc Spelle Venhaus Mtv Gifhorn,1.20,6.13,13.70,3.5,1.81,1.81
20,Hannoverscher Sc Usi Lupo - Martini,6.37,4.41,1.47,2.5,1.96,1.71
21,Asko Kottmannsdorf Ask Klagenfurt,3.09,3.53,2.16,2.5,1.91,1.76
22,Osterlen Ff Fc Rosengayr.,21.00,4.51,1.24,3.5,2.21,1.57
23,Kjelsas 2 Os,4.17,1.81,3.53,6.5,2.11,1.62
24,Tsv Steinbach Ii Baunatal,6.13,4.51,1.44,5.5,1.81,1.81
25,Sv 1898 Unter Flockenbach Eintracht Frankfurt Ii,9.80,6.37,1.23,3.5,1.76,1.86
26,Al Yarmouk Al Baqaa,1.08,9.31,29.00,3.5,2.06,1.62
27,Fc Bgu Minsk Traktor,1.44,4.17,7.60,4.5,2.11,1.62
28,Silver Strikers Karonga United,2.21,2.25,5.68,1.5,1.37,2.70
29,Jeanne D Arc Drancy M19 Montfermeil M19,14.70,6.13,1.20,3.5,1.49,2.35
30,Lens M19 Gonfreville Esm U19,1.34,4.90,7.84,3.5,1.71,1.91
31,Strasbourg M19 Fc 93 Bobigny Bg U19,5.52,4.38,1.61,3.5,1.76,1.86
32,Torcy Val Maubuee M19 Auxerre M19,7.10,4.17,1.44,2.5,2.30,1.49
33,Paris Fc M19 Dijon Asptt M19,1.42,4.41,9.90,2.5,1.49,2.35
34,Sc Air Bel U19 Colomiers M19,3.68,3.09,2.11,1.5,2.35,1.49
35,Orleans M19 Dunkerque M19,1.57,3.92,5.49,3.5,1.54,2.21
36,Amiens M19 Valenciennes M19,2.16,3.14,3.43,4.5,1.52,2.25
37,Drogheda United M19 Bray Wanderers M19,2.01,3.43,3.53,2.5,1.67,1.96
38,Sampdoria W Inter Milan W,6.37,3.23,1.67,1.5,1.96,1.67
39,Sturm Graz W Usc Landhaus W,8.82,3.92,1.42,2.5,1.67,1.96
40,Vsk Aarhus W Brondby W,12.70,5.19,1.24,6.5,2.01,1.67
41,Kaizer Chiefs Reserve Chippa United Reserve,3.82,1.81,3.97,2.5,2.06,1.67
42,Spvg Schonnebeck 1910 1 Fc Kleve,1.34,4.90,8.08,3.5,1.71,1.91
43,Sportfreunde Baumberg Weiss Essen,5.49,3.72,1.62,3.5,1.49,2.35
44,Sv Sonsbeck 1.fc Monheim,1.73,4.07,4.81,3.5,1.76,1.91
45,Fc Polissya Bukovyna,1.00,76.00,270.00,2.5,1.71,1.91

In [7]:
mozzart()

,teams,1_moz,X_moz,2_moz,goals_mz,under_mz,over_mz
0,Andora Letonia,5.00,2.89,1.97,1.5,1.86,1.76
1,Burgos Cf Levante,4.70,2.08,2.74,0.5,2.55,1.47
2,Moldavia Liechtenstein,1.22,5.39,19.60,2.5,1.54,2.21
3,Plymouth Argyle Ipswich Town,1.13,6.37,69.00,3.5,1.27,3.43
4,Chengdu Rongcheng Henan Jianye,3.28,1.88,4.36,0.5,2.16,1.57
5,Krasnodar B Neftekhimik,3.14,2.01,3.92,0.5,2.45,1.47
6,Akron Tolyatti Fk Ufa,2.70,2.89,2.79,1.5,2.16,1.57
7,Shinnik Fk Rubin Kazan,1.00,1.00,1.00,1.0,1.00,1.00
8,Fc Forte Taganrog Fc Chayka Peschanokopskoye,4.26,3.04,1.96,2.5,1.52,2.25
9,Orenburg 2 Khimik Avgust Vurnari,1.00,1.00,1.00,1.0,1.00,1.00
10,Teutonia Ottensen 1905 Rehden,3.58,2.55,2.50,3.5,1.76,1.86
11,Kieler Sv Holstein B Kickers Emden,1.00,147.00,294.00,6.5,1.67,1.96
12,Hildesheim Bremer Sv 1906,1.00,1.00,1.00,1.0,1.00,1.00
13,Bayburt Ozel Idare Sk Arnavutkoy Belediyesi G...,8.08,1.34,5.10,2.5,1.34,2.79
14,Sivas Dort Afjet Afyonspor,16.70,4.51,1.27,1.5,2.50,1.47
15,Hekimoglu Trabzon Karacabey Belediyespor As,2.74,2.06,4.61,0.5,2.50,1.47
16,Zonguldak Iskenderun Fk,1.67,3.23,6.13,2.5,1.57,2.16
17,Sariyer Serik Belediyespor,2.35,2.99,3.19,1.5,2.40,1.47
18,Siegen Westfalia Rhynern,5.00,4.07,1.62,2.5,1.91,1.76
19,Bergisch Gl. Fc Ha1rth,1.57,4.07,5.29,2.5,1.76,1.86
20,Asc 09 Dortmund 1. Fc Gievenbeck,1.54,4.26,5.29,2.5,2.06,1.62
21,Sc Spelle Venhaus Mtv Gifhorn,1.16,7.35,13.20,4.5,1.52,2.25
22,Hannoverscher Sc Usi Lupo 1 Martini,5.88,4.85,1.44,3.5,1.57,2.16
23,Asko Kottmannsdorf Ask Klagenfurt,3.14,3.82,2.06,3.5,1.52,2.25
24,Osterlen Ff Fc Rosengayr.,12.70,4.31,1.32,4.5,1.52,2.25
25,Kjelsas 2 Os,1.44,3.87,8.08,6.5,1.67,2.01
26,Tsv Steinbach Ii Baunatal,1.00,1.00,1.00,1.0,1.00,1.00
27,Sv 1898 Unter Flockenbach Eintracht Frankfurt Ii,1.00,1.00,1.00,1.0,1.00,1.00
28,Al Yarmouk Al Baqaa,1.49,3.97,6.62,3.5,1.47,2.35
29,Fc Bgu Minsk Traktor,1.44,4.21,7.35,4.5,2.21,1.54

## PREMATCH

In [10]:
'''Navigator Options'''
url_mozart_all = 'https://www.mozzartbet.com/en#/date/three_days'

options = Options()
options.add_argument('window-size=1920x1080') #Headless = True
options.headless = True #for not opening the navigator


moz_pre = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
moz_pre.get(url_mozart_all)

C:\Users\KNL\AppData\Local\Temp\ipykernel_25768\143309135.py:9: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  moz_pre = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [11]:
''' MOZZART PREMATCH FUNCTION ''' 
def mozzart_pre():
    df_moz_pre = pd.DataFrame(columns=['teams', '1_mz', 'X_mz', '2_mz', 'under 2.5_mz', 'over 2.5_mz'])
    element = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[4]')
    #time.sleep(10
    #print('scrolling start')

    for i in range(50):
        for j in range(40):
            try:
                element.location_once_scrolled_into_view
                element = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j))
                element2 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')
                
                teams = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[2:4]

                mz_1 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[4]
                mz_X = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[5]
                mz_2 = moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[6]

                mz_under =  moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[10]
                mz_over =  moz_pre.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section[2]/div/div[1]/section[1]/div/div[2]/div[{}]/article[{}]'.format(i,j)).text.split('\n')[12]
                
                df_moz_pre.loc[len(df_moz_pre.index)] = [teams, mz_1, mz_X, mz_2, mz_under, mz_over]
                
                #print(teams, '       |',mz_1,'|', mz_X,'|', mz_2, '|', mz_under, '|', mz_over)
            except:
                pass
    return df_moz_pre

In [12]:
mozzart_pre()

scrolling start

,teams,1_mz,X_mz,2_mz,under 2.5_mz,over 2.5_mz
0,"[Belgium, Wales]",1.42,4.70,9.00,2.08,1.75
1,"[Croatia, Denmark]",2.55,3.10,3.20,1.70,2.15
2,"[France, Austria]",1.40,4.90,9.00,2.24,1.65
3,"[Poland, Netherlands]",3.60,3.50,2.15,1.95,1.85
4,"[Scotland, Ukraine]",2.55,3.05,2.95,1.55,2.30
...,...,...,...,...,...,...
134,"[Rudar V., Lendava]",3.40,3.35,2.05,2.03,1.70
135,"[Anyang, Daejeon Citizen]",2.35,3.25,2.90,1.96,1.75
136,"[Seoul E., Gyeongnam FC]",2.80,3.20,2.45,1.85,1.85
137,"[San Antonio, Colorado Springs]",1.63,3.90,4.40,1.91,1.70
138,"[Fenix, Defensor Sporting]",3.20,3.10,2.25,1.69,2.05

# -------------------------------------------------------------------------------------------

# Tennis LIVE

In [3]:
'''Navigator Options               MOZZART LIVE'''
options = Options()
options.headless = True #for not opening the navigator
options.add_argument('window-size=1920x1080') #Headless = True
url_mozart_tenis = 'https://www.mozzartbet.com/en#/live/sport/5'
moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)
moz.get(url_mozart_tenis)
moz.set_window_size(1920, 1080)

C:\Users\KNL\AppData\Local\Temp\ipykernel_27688\2275845548.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  moz = webdriver.Chrome(r'C:\Users\KNL\Desktop\Ale\Upwork\Scraping_bets\chromedriver.exe', options=options)

In [29]:
for idx, i in enumerate(elemento):
    print(idx, i)
len(elemento)

0 3. set
1 W60 Vrnjacka Banja
2 Radivojevic, Lola
3 Cadantu A.
4 1
5 1
6 4
7 6
8 6
9 2
10 1
11 4
12 30
13 40
14 7.84
15 1.03
16 2.5
17 1.62
18 2.06
19 25.5
20 2.06
21 1.62
22 -
23 -
24 -
25 -
26 -
27 -
28 -
29 -
30 12

31

In [17]:
elemento = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[5]').text.split('\n')

for idx, i in enumerate(elemento):
    print(idx, i)
len(elemento)

0 2. set
1 CHL Braga
2 Sels, Jelle
3 Shevchenko, Alexander
4 1
5 0
6 7
7 6
8 6
9 6
10 5
11 5
12 1.34
13 2.89
14 -1.5
15 1.39
16 2.60
17 29.5
18 1.81
19 1.81
20 2. Set
21 1.81
22 1.81
23 -
24 -
25 -
26 -
27 -
28 -
29 23

30

Voy a tener que ver, en que set van y en función de eso el valor de subindice que obtiene.

In [16]:
elemento = moz.find_element(By.XPATH, '/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[1]').text.split('\n')
print(elemento[2]+' vs '+elemento[3], )

Ruud C. vs Sock J.

In [21]:
def mozzart_tenis():
    df_moz_tenis = pd.DataFrame(columns=['players', '1_moz', '2_moz', 'games_moz', 'under_moz', 'over_moz'])
    for i in range(30):
        try:
            elemento = moz.find_element(By.XPATH, f'/html/body/div[1]/div[1]/section/section/div[1]/section/section/div/div[1]/div/section/div/article[{i}]').text.split('\n')
            players = elemento[2]+' vs '+ elemento[3]
            set = elemento[0]
            if len(elemento)== 30:
                moz_1 = elemento[10].replace('-','1')
                moz_2 = elemento[11].replace('-','1')
                games = elemento[15]
                under_moz = elemento[16]
                over_moz = elemento[17]
            if len(elemento) == 31:
                moz_1 = elemento[14].replace('-','1')
                moz_2 = elemento[15].replace('-','1')
                games = elemento[19]
                under_moz = elemento[20]
                over_moz = elemento[21]

            if len(elemento)== 32:
                moz_1 = elemento[12].replace('-','1')
                moz_2 = elemento[13].replace('-','1')
                games = elemento[17]
                under_moz = elemento[18]
                over_moz= elemento[19]
            
            ''' 4 players matches'''
            if '/' in players:
                if '1.' in set:
                    moz_1 = elemento[10].replace('-','1')
                    moz_2 = elemento[11].replace('-','1')
                    games = elemento[15]
                    under_moz = elemento[16].replace('-','1')
                    over_moz = elemento[17].replace('-','1')
                elif '2.' in set:
                    moz_1 = elemento[12].replace('-','1')
                    moz_2 = elemento[13].replace('-','1')
                    games = elemento[17]
                    under_moz=elemento[18]
                    over_moz = elemento[19]

            #print(set, players,'  || ', moz_1,'/', moz_2,'|', games,  under_moz,'/',over_moz, '|| article:',i, 'len:', len(elemento))
            df_moz_tenis.loc[len(df_moz_tenis.index)] = [players, moz_1, moz_2, games, under_moz, over_moz]
                
            
        except:
            pass
    return df_moz_tenis

In [29]:
for a in range(3):
    clear_output()
    display(mozzart_tenis())
    time.sleep(2)

,players,1_moz,2_moz,games_moz,under_moz,over_moz
0,Tsitsipas S. vs Schwartzm.d.,1.03,7.60,17.5,1.47,2.40
1,Dodin O. vs Tomova V.,1.91,1.76,27.5,1.67,2.01
2,Casanova H. vs Bagins F.,8.58,1.04,18.5,2.25,1.52
3,"Hijikata, Rinky vs Stricker, Dominic Stephan",5.10,1.12,20.5,1.91,1.71
4,"Vukic A. vs Cannon, Kingsley",2.84,1.34,22.5,1.76,1.86
5,Lukas T. vs Bolsova A.,2.84,1.34,22.5,1.76,1.86
6,Rinaldo K. vs Benoit M.,1.32,2.89,26.5,1.96,1.71
7,In-albon Y. vs Bilardo F.,1.32,2.94,27.5,1.62,2.06
8,"Ewing, Salma vs Dagan Fruchtman, Mika",1.23,3.48,25.5,2.01,1.67
9,"Colling, Solymar vs Rodriguez V.",1.08,5.78,27.5,1.62,2.06
10,"Mukhortova, Alina vs Proctor, Lauren",2.89,1.32,30.5,1.81,1.81
11,"Becerra A. vs Ulyashchenko, Anna",12.3,1,-,-,-
12,"Rivera Corado, Maria Gabriela vs Koike, Ena",2.40,1.47,29.5,1.71,1.91
13,"Herazo M. vs Mdlulwa, Wozuko",2.40,1.47,29.5,1.71,1.91
14,"Romero, Camila vs San Martin Ramirez, Valeska ...",1,29.0,14.5,2.06,1.62
15,"Dorcil, Sydney vs Ccuno , Romina",12.3,1,14.5,2.21,1.54
16,"Samudio, Antonia vs Sewing, Sofia",5.10,1.10,18.5,1.81,1.81
17,"Lavagno, Edoa. vs Calvano, Giovanni",1.03,12.7,18.5,1.96,1.71
18,"Wallin, Olle vs Lyeons, Jaycer",1.34,2.84,22.5,1.81,1.81
19,"Azoides, Demetris vs Bicknell, Blaise",3.09,1.27,21.5,1.86,1.76
20,Margaroli L / Ramanathan R vs Kravchenko G / N...,1.32,3.09,-,-,-
21,Nedunchezhiyan J / Rungkat C vs Rocha H / Rodr...,1,19.6,22.5,1.08,5.49
22,Curovic T / Radivojevic L vs Astakhova D / Rey...,3.63,1.23,18.5,1.71,1.96
23,Tabacco F / Tabacco G vs Sakellaridis D / Sake...,1.27,3.19,20.5,1.62,2.11